name: 🔍 DGuard Audit Trigger

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  trigger-audit:
    name: Trigger DGuard Audit Bot
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.pull_request.draft == false }}
    
    steps:
      - name: 🚀 Trigger External Audit
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = {
              event_type: github.event_name === 'pull_request' ? 'dguard-pr-opened' : 'dguard-push',
              client_payload: {
                repository: context.repo.owner + '/' + context.repo.repo,
                pr_number: context.payload.pull_request?.number || null,
                action: context.payload.action || 'push',
                ref: context.ref,
                sha: context.sha,
                sender: context.payload.sender?.login || 'unknown',
                event_name: github.event_name
              }
            };
            
            console.log('🔍 Triggering DGuard Ultra Audit Bot...');
            console.log('Repository:', payload.client_payload.repository);
            console.log('Event Type:', payload.event_type);
            console.log('PR Number:', payload.client_payload.pr_number);
            
            try {
              await github.rest.repos.createDispatchEvent({
                owner: 'Santy1422',
                repo: 'dguard-audit-bot',
                ...payload
              });
              
              console.log('✅ DGuard audit triggered successfully');
              
              // Post initial comment on PR if it's a PR event
              if (github.event_name === 'pull_request' && context.payload.pull_request?.number) {
                try {
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.payload.pull_request.number,
                    body: `## 🤖 DGuard Ultra Audit Bot
                    
🔍 **Análisis iniciado automáticamente**

El DGuard Ultra Audit Bot está analizando este PR. Los resultados aparecerán aquí en breve.

### 🔧 Análisis en progreso:
- ✅ Detección de endpoints y APIs
- ✅ Validación de seguridad y autenticación  
- ✅ Análisis de llamadas entre frontend y backend
- ✅ Sugerencias de optimización AI-powered

**Tiempo estimado:** 2-3 minutos

---
*Este comentario se actualizará automáticamente con los resultados.*`
                  });
                  
                  console.log('📝 Initial comment posted to PR');
                } catch (commentError) {
                  console.log('⚠️ Could not post initial comment:', commentError.message);
                }
              }
              
            } catch (error) {
              console.error('❌ Failed to trigger audit:', error.message);
              core.setFailed('Failed to trigger DGuard audit: ' + error.message);
            }